/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JAppletMain.java
 *
 * Created on 26/Out/2011, 16:29:25
 */
package Interface;

import Config.StringHtml;
import XML.QueryXML;
import XML.QueryXML_Lingua;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.xml.xpath.XPathExpressionException;
import mvc.Observer;

/**
 *
 * @author Miguel
 */
public class JAppletMain extends javax.swing.JApplet implements Observer {
    
    QueryXML _q;
    QueryXML_Lingua _l;
    DecimalFormat df = new DecimalFormat("#.##");

    /** Initializes the applet JAppletMain */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //JOptionPane.showMessageDialog(rootPane, info.getName());
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAppletMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAppletMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAppletMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAppletMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                
                @Override
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
        }

        // meu código
        carregarBD();
        preencherTipoMateriais();
        configs();
        jRadioButtonPT.setSelected(true);
    }
    
    private void carregarBD() {

        //URL base = getDocumentBase();
        //URL xmlBD = new URL(base, "DataBase.xml");

        //JOptionPane.showConfirmDialog(rootPane, "URL: " + base.toString());
        //JOptionPane.showConfirmDialog(rootPane, "URL: " + xmlBD.toString());

        /*não está a ser usado o xmlBD*/
        _q = new QueryXML();
        _l = new QueryXML_Lingua();
        
    }
    
    private void configs() {
        String tm = _l.queryText("main", "jLabelTipoMaterial");
        String tm_desc = _l.queryText("main", "jLabelTipoMaterial_desc");
        String v = _l.queryText("main", "jLabelTotal_desc");

        //System.out.println(tm + "\n" + tm_desc + "\n" + v);

        jLabelTipoMaterial.setText(tm);
        jLabelTipoMaterial.setToolTipText(StringHtml.html_toolTipText(tm_desc));
        jLabelTotal.setToolTipText(StringHtml.html_toolTipText(v));
        jLabelTotalValor.setToolTipText(StringHtml.html_toolTipText(v));
    }

    /****************************************/
    /*      PREENCHER COMBO BOX             */
    /****************************************/
    private void preencherTipoMateriais() {
        
        jComboBoxTipoMaterial.removeAllItems();
        jComboBoxTipoMaterial.addItem("");
        try {
            ArrayList<String> tipo_materiais = _q.queryTipoMateriais();
            
            for (String s : tipo_materiais) {
                jComboBoxTipoMaterial.addItem(s);
                System.out.println(s);
            }
        } catch (XPathExpressionException ex) {
            Logger.getLogger(JAppletMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelTipoMaterial = new javax.swing.JLabel();
        jComboBoxTipoMaterial = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonPT = new javax.swing.JRadioButton();
        jRadioButtonFR = new javax.swing.JRadioButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTotalValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelTipoMaterial = new javax.swing.JPanel();
        jLabelTotal = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTipoMaterial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTipoMaterial.setText("Escolha o tipo de material:");

        jComboBoxTipoMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoMaterialItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoMaterial, 0, 341, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoMaterial)
                    .addComponent(jComboBoxTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jRadioButtonPT.setText("Português");
        jRadioButtonPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(jRadioButtonPT, gridBagConstraints);

        jRadioButtonFR.setText("Français");
        jRadioButtonFR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFRActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel3.add(jRadioButtonFR, gridBagConstraints);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Lingua");

        jLabelTotalValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTotalValor.setText("€");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(665, 353));

        jPanelTipoMaterial.setBackground(new java.awt.Color(208, 192, 190));
        jPanelTipoMaterial.setAutoscrolls(true);

        javax.swing.GroupLayout jPanelTipoMaterialLayout = new javax.swing.GroupLayout(jPanelTipoMaterial);
        jPanelTipoMaterial.setLayout(jPanelTipoMaterialLayout);
        jPanelTipoMaterialLayout.setHorizontalGroup(
            jPanelTipoMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        jPanelTipoMaterialLayout.setVerticalGroup(
            jPanelTipoMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelTipoMaterial);

        jLabelTotal.setText("TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalValor)
                    .addComponent(jLabelTotal))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /****************************************/
    /*         MUDA O TIPO DE MATERIAL              */
    /****************************************/
    private void jComboBoxTipoMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoMaterialItemStateChanged
        
        String tipo_material = materialSeleccionado();
        _q.setTipoMaterial(tipo_material);
        jComboBoxTipoMaterial.setToolTipText(tipo_material);
        
        if (tipo_material.equalsIgnoreCase("pedra") || tipo_material.equalsIgnoreCase("Mármores e Granitos")) {
            jLabelTotalValor.setText("0");
            if (jPanelTipoMaterial.getComponents().length > 0) {
                jPanelTipoMaterial.removeAll();
            }
            
            JPanelPedra j = new JPanelPedra(_q, tipo_material);
            j.addObserver(this);
            jPanelTipoMaterial.add(j);
            jPanelTipoMaterial.repaint();
            jPanelTipoMaterial.revalidate();
            
            jPanelTipoMaterial.setLayout(new BoxLayout(jPanelTipoMaterial, BoxLayout.X_AXIS));
            jPanelTipoMaterial.repaint();
            jPanelTipoMaterial.revalidate();

            //JOptionPane.showMessageDialog(rootPane, "Tipo Material entrou: " + tipo_material);
        } else if (tipo_material.equalsIgnoreCase("Lambrim e Balcão")) {
            jLabelTotalValor.setText("0");
            if (jPanelTipoMaterial.getComponents().length > 0) {
                jPanelTipoMaterial.removeAll();
            }
            
            JPanelEcoLeather j = new JPanelEcoLeather(_q, tipo_material);
            j.addObserver(this);
            jPanelTipoMaterial.add(j);
            jPanelTipoMaterial.repaint();
            jPanelTipoMaterial.revalidate();
            
            jPanelTipoMaterial.setLayout(new BoxLayout(jPanelTipoMaterial, BoxLayout.X_AXIS));
            jPanelTipoMaterial.repaint();
            jPanelTipoMaterial.revalidate();
        } else {
            jLabelTotalValor.setText("0");
            if (jPanelTipoMaterial.getComponents().length > 0) {
                jPanelTipoMaterial.removeAll();
            }
            JPanelNada j = new JPanelNada();
            jPanelTipoMaterial.add(j);
            jPanelTipoMaterial.setLayout(new BoxLayout(jPanelTipoMaterial, BoxLayout.X_AXIS));
            
        }
        jPanelTipoMaterial.revalidate();
        
    }//GEN-LAST:event_jComboBoxTipoMaterialItemStateChanged
    
    private void jRadioButtonPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPTActionPerformed
        jRadioButtonPT.setSelected(true);
        jRadioButtonFR.setSelected(false);
        _l.setLingua("pt");
        configs();
    }//GEN-LAST:event_jRadioButtonPTActionPerformed
    
    private void jRadioButtonFRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFRActionPerformed
        jRadioButtonPT.setSelected(false);
        jRadioButtonFR.setSelected(true);
        _l.setLingua("fr");
        configs();
    }//GEN-LAST:event_jRadioButtonFRActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxTipoMaterial;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTipoMaterial;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelTipoMaterial;
    private javax.swing.JRadioButton jRadioButtonFR;
    private javax.swing.JRadioButton jRadioButtonPT;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /************* Funcões auxiliaures *******************/
    private String materialSeleccionado() {
        String m = "";
        try {
            m += jComboBoxTipoMaterial.getSelectedItem().toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro");
        }
        return m;
    }
    
    @Override
    public void update(String n) {
    }
    
    @Override
    public void update(String material, String cor) {
    }
    
    @Override
    public void update(String n, Double v) {
        jLabelTotalValor.setText(df.format(v).toString());
    }
}
