/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameImagens.java
 *
 * Created on 19/Dez/2011, 0:12:10
 */
package Interface;

import XML.QueryXML;
import XML.QueryXML_Lingua;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.TreeMap;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author miguel
 */
public class JFrameImagens extends javax.swing.JFrame {

    QueryXML _q;
    QueryXML_Lingua _l;
    TreeMap<String, String> _imgs_silestone;
    private DefaultComboBoxModel _silestone = new DefaultComboBoxModel();

    /** Creates new form JFrameImagens */
    public JFrameImagens(QueryXML q, QueryXML_Lingua l) {
        initComponents();
        centerOnScreen(this);
        _q = q;
        _l = l;

        imagens_silestone();
    }

    private void imagens_silestone() {
        _silestone = new DefaultComboBoxModel();
        jComboBox1.setModel(_silestone);
        _imgs_silestone = _q.queryImagem_NomeEPath("silestone");

        for (String n : _imgs_silestone.keySet()) {
            _silestone.addElement(n);
        }

    }

    private void procura_silestone() {
        try {
            imagens_silestone();
            String n = jTextFieldSilestone.getText().toString();
            if (n.equals("") || n == null) {
                imagens_silestone();
                return;
            } else {
                _silestone.removeAllElements();
                for (String nome : _imgs_silestone.keySet()) {
                    if (nome.contains(n)) {
                        _silestone.addElement(nome);
                    }
                }
            }
        } catch (Exception e) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneSilestone = new javax.swing.JTabbedPane();
        jPanelSilestone = new javax.swing.JPanel();
        jPanelSilestoneProcura = new javax.swing.JPanel();
        jTextFieldSilestone = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelSilestone = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setResizable(false);

        jPanelSilestoneProcura.setBackground(new java.awt.Color(245, 245, 245));
        jPanelSilestoneProcura.setPreferredSize(new java.awt.Dimension(390, 416));

        jTextFieldSilestone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSilestoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSilestoneKeyReleased(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelSilestone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelSilestoneProcuraLayout = new javax.swing.GroupLayout(jPanelSilestoneProcura);
        jPanelSilestoneProcura.setLayout(jPanelSilestoneProcuraLayout);
        jPanelSilestoneProcuraLayout.setHorizontalGroup(
            jPanelSilestoneProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSilestoneProcuraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSilestoneProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSilestone, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSilestoneProcuraLayout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, 570, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSilestone, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelSilestoneProcuraLayout.setVerticalGroup(
            jPanelSilestoneProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSilestoneProcuraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSilestoneProcuraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSilestone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSilestone, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelSilestoneLayout = new javax.swing.GroupLayout(jPanelSilestone);
        jPanelSilestone.setLayout(jPanelSilestoneLayout);
        jPanelSilestoneLayout.setHorizontalGroup(
            jPanelSilestoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSilestoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSilestoneProcura, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSilestoneLayout.setVerticalGroup(
            jPanelSilestoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSilestoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSilestoneProcura, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneSilestone.addTab("Silestone", jPanelSilestone);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPaneSilestone.addTab("Mármores", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPaneSilestone.addTab("Granitos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSilestone, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneSilestone, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            String n = jComboBox1.getSelectedItem().toString();
            String p = _imgs_silestone.get(n);

            jLabelSilestone.setIcon(new javax.swing.ImageIcon(getClass().getResource(p)));
            jLabelSilestone.setText("");
        } catch (Exception e) {
            jLabelSilestone.setText("Sem imagem para mostrar.");
            jLabelSilestone.setIcon(null);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextFieldSilestoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSilestoneKeyPressed
        //procura_silestone();
    }//GEN-LAST:event_jTextFieldSilestoneKeyPressed

    private void jTextFieldSilestoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSilestoneKeyReleased
        procura_silestone();
    }//GEN-LAST:event_jTextFieldSilestoneKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameImagens(null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabelSilestone;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelSilestone;
    private javax.swing.JPanel jPanelSilestoneProcura;
    private javax.swing.JTabbedPane jTabbedPaneSilestone;
    private javax.swing.JTextField jTextFieldSilestone;
    // End of variables declaration//GEN-END:variables


 public static void centerOnScreen(final Component target) {
       if (target != null) {
           Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
           Dimension dialogSize = target.getSize();

           if (dialogSize.height > screenSize.height) {
               dialogSize.height = screenSize.height;
           }
           if (dialogSize.width > screenSize.width) {
               dialogSize.width = screenSize.width;
           }

           target.setLocation((screenSize.width - dialogSize.width) / 2,
                   (screenSize.height - dialogSize.height) / 2);
       }
   }


}
