/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPedraPeca.java
 *
 * Created on 8/Nov/2011, 12:33:43
 */
package Interface;

import Config.StringHtml;
import XML.QueryXML;
import XML.QueryXML_Lingua;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import mvc.Observer;
import mvc.Subject;

/**
 *
 * @author miguel
 */
public class JPanelEcoLeatherRodamao extends javax.swing.JPanel implements Subject, Observer {

    private String _material;
    private QueryXML _q;
    private QueryXML_Lingua _l;
    private DecimalFormat df = new DecimalFormat("#.##");
    private ArrayList<Observer> observers = new ArrayList<Observer>();
    // para não estar a fazer uma query sempre, fica aqui os precos com as cores
    private TreeMap<String, Double> rodamaos_e_precos = new TreeMap<String, Double>();
    private String _rodamaos = "";

    /** Creates new form JPanelPedraPeca */
    public JPanelEcoLeatherRodamao(QueryXML q, QueryXML_Lingua l, String material) {
        initComponents();
        _q = q;
        _l = l;
        _material = material;
        configs();
        configs_lng();
        valores();
    }

    private void configs() {
        SpinnerNumberModel modelSpinnerC = new SpinnerNumberModel(0, 0, 100000, 1);
        jSpinnerNumero.setModel(modelSpinnerC);

        
    }
    
    public void configs_lng(){
        /*
        jLabelRodamao.setText(_l.queryText("ecoleatherAcabamento", "jLabelAcabamento"));
        jLabelRodamao.setToolTipText(_l.queryText("ecoleatherAcabamento", "jLabelAcabamento_desc"));
        jLabelComprimento.setText(_l.queryText("ecoleatherAcabamento", "jLabelComprimento"));
        jLabelComprimento.setToolTipText(_l.queryText("ecoleatherAcabamento", "jLabelComprimento_desc"));
        jLabelTOTAL.setText(_l.queryText("ecoleatherAcabamento", "jLabelTotal"));
        */

    }

    private void valores() {
        rodamaos_e_precos.clear();
        rodamaos_e_precos = _q.queryRodamaos_NomeEPreco(_material);
        
        jComboBoxRodamao.removeAllItems();
        for (String s : rodamaos_e_precos.keySet()) {
            jComboBoxRodamao.addItem(s);
        }
    }

    public void actualizarTotal() {
        try {
            int dim = Integer.parseInt(jSpinnerNumero.getValue().toString());

            Double preco_acabamento = rodamaos_e_precos.get(_rodamaos);

            Double dim_cm = dim / 100.0; // porque está em cm e o preço em m
            Double preco_total = dim_cm * preco_acabamento;

            jLabelTOTALValor.setText(df.format(preco_total).toString());
        } catch (Exception e) {
        }
    }

    public Double getTotal() {
        Double valor = 0.0;
        try {
            String v = jLabelTOTALValor.getText();
            v = v.replace(",", ".");
            valor = Double.parseDouble(v);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: getTotal() em JPanelEcoLeatherRodamao.java" + e.getMessage());
        }
        return valor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRodamao = new javax.swing.JLabel();
        jLabelComprimento = new javax.swing.JLabel();
        jComboBoxRodamao = new javax.swing.JComboBox();
        jSpinnerNumero = new javax.swing.JSpinner();
        jLabelTOTAL = new javax.swing.JLabel();
        jLabelTOTALValor = new javax.swing.JLabel();
        jLabelRodamaoPreco = new javax.swing.JLabel();

        jLabelRodamao.setText("Rodamão:");

        jLabelComprimento.setText("cm:");

        jComboBoxRodamao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRodamaoItemStateChanged(evt);
            }
        });

        jSpinnerNumero.setMaximumSize(new java.awt.Dimension(36, 26));
        jSpinnerNumero.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerNumeroStateChanged(evt);
            }
        });

        jLabelTOTAL.setFont(new java.awt.Font("Ubuntu", 1, 12));
        jLabelTOTAL.setText("TOTAL (€):");

        jLabelTOTALValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTOTALValor.setText("€");

        jLabelRodamaoPreco.setText("€/m");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRodamao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxRodamao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRodamaoPreco)
                .addGap(32, 32, 32)
                .addComponent(jLabelComprimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabelTOTAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTOTALValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRodamao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRodamao)
                    .addComponent(jLabelTOTALValor)
                    .addComponent(jLabelTOTAL)
                    .addComponent(jLabelRodamaoPreco)
                    .addComponent(jSpinnerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComprimento)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerNumeroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNumeroStateChanged
        actualizarTotal();
        notifyObservers("rodamao");
    }//GEN-LAST:event_jSpinnerNumeroStateChanged

    private void jComboBoxRodamaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRodamaoItemStateChanged
        try {
            _rodamaos = jComboBoxRodamao.getSelectedItem().toString();
            String acabamento = StringHtml.html_toolTipText(_rodamaos);
            jComboBoxRodamao.setToolTipText(acabamento);

            Double d = rodamaos_e_precos.get(_rodamaos);
            String valor = d.toString() + " €/m";
            jLabelRodamaoPreco.setText(valor);

            actualizarTotal();
            notifyObservers("rodamao");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBoxRodamaoItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxRodamao;
    private javax.swing.JLabel jLabelComprimento;
    private javax.swing.JLabel jLabelRodamao;
    private javax.swing.JLabel jLabelRodamaoPreco;
    private javax.swing.JLabel jLabelTOTAL;
    private javax.swing.JLabel jLabelTOTALValor;
    private javax.swing.JSpinner jSpinnerNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addObserver(Observer o) {
        observers.add(o);
    }

    @Override
    public void removeObserver(Observer o) {
        observers.remove(o);
    }

    @Override
    public void notifyObservers(String n) {
        Iterator<Observer> it = observers.iterator();
        while (it.hasNext()) {
            Observer observer = it.next();
            observer.update(n);
        }
    }

    @Override
    public void notifyObservers(String material, String cor) {
    }

    @Override
    public void update(String n) {
        if(n.equalsIgnoreCase("lng")){
            configs_lng();
        }
        actualizarTotal();
    }

    @Override
    public void update(String material, String cor) {
        _material = material;
        valores();
        actualizarTotal();
    }

    @Override
    public void notifyObservers(String n, Double d) {
    }

    @Override
    public void update(String n, Double v) {
    }
    
}

