/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPedraPeca.java
 *
 * Created on 8/Nov/2011, 12:33:43
 */
package Interface;

import XML.QueryXML;
import XML.QueryXML_Lingua;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import mvc.Observer;
import mvc.Subject;

/**
 *
 * @author miguel
 */
public class JPanelEcoLeatherLadrilhosPeca extends javax.swing.JPanel implements Subject, Observer {

    private String _material = "Ladrilhos";
    private String _cor;
    private String _dim = "";
    private QueryXML _q;
    private QueryXML_Lingua _l;
    private DecimalFormat df = new DecimalFormat("#.##");
    private ArrayList<Observer> observers = new ArrayList<Observer>();
    private HashMap<String, Double> dimensoes_e_precos = new HashMap<String, Double>();

    /** Creates new form JPanelPedraPeca */
    public JPanelEcoLeatherLadrilhosPeca(QueryXML q, QueryXML_Lingua l, String cor) {
        initComponents();
        _q = q;
        _l = l;
        _cor = cor;
        configs();
        configs_lng();
        valores();
    }

    private void configs() {
        SpinnerNumberModel modelSpinnerC = new SpinnerNumberModel(0, 0, 1000000000, 1);
        jSpinnerComprimento.setModel(modelSpinnerC);

        jLabelDim.setName("jLabelLargura");
        jLabelComprimento.setName("jLabelComprimento");
        jLabelTOTAL.setName("jLabelTOTAL");
        jLabelTOTALValor.setName("valor");

        jLabelComprimento.setToolTipText("Comprimento");
    }

    private void configs_lng() {
    }

    private void valores() {
        dimensoes_e_precos = _q.queryLadrilhosPeca_NomeEPreco(_material, _cor);
        jComboBoxDim.removeAllItems();
        for (String s : dimensoes_e_precos.keySet()) {
            jComboBoxDim.addItem(s);
        }
    }

    public void actualizarTotal() {
        try {
            int comp = Integer.parseInt(jSpinnerComprimento.getValue().toString());

            //Double m = comp / 10000.00;

            Double preco_dim = 0.0;

            preco_dim = dimensoes_e_precos.get(_dim);

            Double preco_total = comp * preco_dim;

            jLabelTOTALValor.setText("" + df.format(preco_total));
            this.notifyObservers("LadrilhosPeca");
        } catch (Exception e) {
        }
    }

    public Double getTotal() {
        Double valor = 0.0;
        try {
            String v = jLabelTOTALValor.getText();
            v = v.replace(",", ".");
            valor = Double.parseDouble(v);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: getTotal() em JPanelPedraLinha.java" + e.getMessage());
        }
        return valor;
    }

    public void getLargura() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDim = new javax.swing.JLabel();
        jLabelComprimento = new javax.swing.JLabel();
        jComboBoxDim = new javax.swing.JComboBox();
        jSpinnerComprimento = new javax.swing.JSpinner();
        jLabelTOTAL = new javax.swing.JLabel();
        jLabelTOTALValor = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();

        jLabelDim.setText("Dim:");

        jLabelComprimento.setText("m2:");

        jComboBoxDim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDimItemStateChanged(evt);
            }
        });

        jSpinnerComprimento.setMaximumSize(new java.awt.Dimension(36, 26));
        jSpinnerComprimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerComprimentoStateChanged(evt);
            }
        });

        jLabelTOTAL.setFont(new java.awt.Font("Ubuntu", 1, 12));
        jLabelTOTAL.setText("TOTAL (€):");

        jLabelTOTALValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTOTALValor.setText("€");

        jLabelPreco.setText("€/m2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxDim, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelComprimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabelTOTAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTOTALValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTOTALValor)
                .addComponent(jLabelTOTAL)
                .addComponent(jLabelDim)
                .addComponent(jComboBoxDim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelComprimento)
                .addComponent(jSpinnerComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelPreco))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDimItemStateChanged
        actualizarTotal();
        _dim = jComboBoxDim.getSelectedItem().toString();
        jLabelPreco.setText(dimensoes_e_precos.get(_dim).toString() + "€/m2");

        notifyObservers("LadrilhosPeca");
    }//GEN-LAST:event_jComboBoxDimItemStateChanged

    private void jSpinnerComprimentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerComprimentoStateChanged
        actualizarTotal();
        notifyObservers("LadrilhosPeca");
    }//GEN-LAST:event_jSpinnerComprimentoStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxDim;
    private javax.swing.JLabel jLabelComprimento;
    private javax.swing.JLabel jLabelDim;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelTOTAL;
    private javax.swing.JLabel jLabelTOTALValor;
    private javax.swing.JSpinner jSpinnerComprimento;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addObserver(Observer o) {
        observers.add(o);
    }

    @Override
    public void removeObserver(Observer o) {
        observers.remove(o);
    }

    @Override
    public void notifyObservers(String n) {
        //JOptionPane.showMessageDialog(jLabelComprimento, "Vai notificar! Valor: " + d);
        Iterator<Observer> it = observers.iterator();
        while (it.hasNext()) {
            Observer observer = it.next();
            observer.update(n);
        }
    }

    @Override
    public void update(String n) {
        if (n.equalsIgnoreCase("lng")) {
            configs_lng();
            return;
        }
        actualizarTotal();
    }

    @Override
    public void notifyObservers(String material, String cor) {
    }

    @Override
    public void update(String material, String cor) {
        _material = material;
        _cor = cor;
        actualizarTotal();
    }

    @Override
    public void notifyObservers(String n, Double d) {
    }

    @Override
    public void update(String n, Double v) {
    }
}
