/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPedraPeca.java
 *
 * Created on 8/Nov/2011, 12:33:43
 */
package Interface;

import Config.StringHtml;
import XML.QueryXML;
import XML.QueryXML_Lingua;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import mvc.Observer;
import mvc.Subject;

/**
 *
 * @author miguel
 */
public class JPanelPedraPeca extends javax.swing.JPanel implements Subject, Observer {

    private String _material;
    private String _cor;
    private QueryXML _q;
    private QueryXML_Lingua _l;
    private DecimalFormat df = new DecimalFormat("#.##");
    private ArrayList<Observer> observers = new ArrayList<Observer>();

    /** Creates new form JPanelPedraPeca */
    public JPanelPedraPeca(QueryXML q, QueryXML_Lingua l, String material, String cor) {
        initComponents();
        _q = q;
        _l = l;
        _material = material;
        _cor = cor;
        configs();
        configs_lng();
        valores();
    }

    private void configs() {
        SpinnerNumberModel modelSpinnerL = new SpinnerNumberModel(0, 0, 100000, 1);
        SpinnerNumberModel modelSpinnerC = new SpinnerNumberModel(0, 0, 100000, 1);
        jSpinnerLargura.setModel(modelSpinnerL);
        jSpinnerComprimento.setModel(modelSpinnerC);

        jLabelLargura.setName("jLabelLargura");
        jLabelComprimento.setName("jLabelComprimento");
        jLabelEspessura.setName("jLabelEspessura");
        jLabelTOTAL.setName("jLabelTOTAL");
        jLabelTOTALValor.setName("valor");

        jLabelLargura.setToolTipText("Largura");
        jLabelComprimento.setToolTipText("Comprimento");
        jLabelEspessura.setToolTipText("Espessura");
    }

    private void configs_lng() {

        for (Component c : this.getComponents()) {
            if (c instanceof JLabel && !c.getName().equals("valor")) {
                JLabel j = (JLabel) c;
                String texto = _l.queryText("pedraPeca", j.getName());
                String desc = StringHtml.html_toolTipText(_l.queryText("pedraPeca", j.getName() + "_desc"));
                j.setText(texto);
                j.setToolTipText(desc);
            }
        }
    }

    private void valores() {
        ArrayList<String> esp = _q.queryEspessuras(_material);
        jComboBoxEspessura.removeAllItems();
        for (String e : esp) {
            jComboBoxEspessura.addItem(e);
        }
    }

    public void actualizarTotal() {
        try {
            int larg = Integer.parseInt(jSpinnerLargura.getValue().toString());
            int comp = Integer.parseInt(jSpinnerComprimento.getValue().toString());
            double dim = larg * comp;
            String esp = jComboBoxEspessura.getSelectedItem().toString();

            String unidade_cor = _q.queryCoresUnidade(_material);

            if (unidade_cor.equalsIgnoreCase("m2")) {
                dim = dim / 10000;
            }

            Double preco_cor = 0.0;

            preco_cor = _q.queryCoresPreco(_material, _cor, esp);

            Double preco_total = dim * preco_cor;

            jLabelTOTALValor.setText("" + df.format(preco_total));
            this.notifyObservers("peca");
        } catch (Exception e) {
        }
    }

    public Double getTotal() {
        Double valor = 0.0;
        try {
            String v = jLabelTOTALValor.getText();
            v = v.replace(",", ".");
            valor = Double.parseDouble(v);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro: getTotal() em JPanelPedraLinha.java" + e.getMessage());
        }
        return valor;
    }

    public void getLargura() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLargura = new javax.swing.JLabel();
        jLabelComprimento = new javax.swing.JLabel();
        jLabelEspessura = new javax.swing.JLabel();
        jComboBoxEspessura = new javax.swing.JComboBox();
        jSpinnerLargura = new javax.swing.JSpinner();
        jSpinnerComprimento = new javax.swing.JSpinner();
        jLabelTOTAL = new javax.swing.JLabel();
        jLabelTOTALValor = new javax.swing.JLabel();

        jLabelLargura.setText("Larg. (cm):");

        jLabelComprimento.setText("Comp. (cm):");

        jLabelEspessura.setText("Esp. (cm):");

        jComboBoxEspessura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEspessuraItemStateChanged(evt);
            }
        });

        jSpinnerLargura.setMaximumSize(new java.awt.Dimension(36, 26));
        jSpinnerLargura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerLarguraStateChanged(evt);
            }
        });

        jSpinnerComprimento.setMaximumSize(new java.awt.Dimension(36, 26));
        jSpinnerComprimento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerComprimentoStateChanged(evt);
            }
        });

        jLabelTOTAL.setFont(new java.awt.Font("Ubuntu", 1, 12));
        jLabelTOTAL.setText("TOTAL (€):");

        jLabelTOTALValor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTOTALValor.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabelLargura)
                .addGap(2, 2, 2)
                .addComponent(jSpinnerLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabelComprimento)
                .addGap(2, 2, 2)
                .addComponent(jSpinnerComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabelEspessura)
                .addGap(2, 2, 2)
                .addComponent(jComboBoxEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelTOTAL)
                .addGap(2, 2, 2)
                .addComponent(jLabelTOTALValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelLargura))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jSpinnerLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelComprimento))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jSpinnerComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelEspessura))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jComboBoxEspessura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelTOTAL))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelTOTALValor))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerLarguraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerLarguraStateChanged
        actualizarTotal();
        notifyObservers("peca");
    }//GEN-LAST:event_jSpinnerLarguraStateChanged

    private void jSpinnerComprimentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerComprimentoStateChanged
        actualizarTotal();
        notifyObservers("peca");
    }//GEN-LAST:event_jSpinnerComprimentoStateChanged

    private void jComboBoxEspessuraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEspessuraItemStateChanged
        actualizarTotal();
        notifyObservers("peca");
    }//GEN-LAST:event_jComboBoxEspessuraItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxEspessura;
    private javax.swing.JLabel jLabelComprimento;
    private javax.swing.JLabel jLabelEspessura;
    private javax.swing.JLabel jLabelLargura;
    private javax.swing.JLabel jLabelTOTAL;
    private javax.swing.JLabel jLabelTOTALValor;
    private javax.swing.JSpinner jSpinnerComprimento;
    private javax.swing.JSpinner jSpinnerLargura;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addObserver(Observer o) {
        observers.add(o);
    }

    @Override
    public void removeObserver(Observer o) {
        observers.remove(o);
    }

    @Override
    public void notifyObservers(String n) {
        //JOptionPane.showMessageDialog(jLabelComprimento, "Vai notificar! Valor: " + d);
        Iterator<Observer> it = observers.iterator();
        while (it.hasNext()) {
            Observer observer = it.next();
            observer.update(n);
        }
    }

    @Override
    public void update(String n) {
        if (n.equalsIgnoreCase("lng")) {
            configs_lng();
            return;
        }
        actualizarTotal();
    }

    @Override
    public void notifyObservers(String material, String cor) {
    }

    @Override
    public void update(String material, String cor) {
        _material = material;
        _cor = cor;
        actualizarTotal();
    }

    @Override
    public void notifyObservers(String n, Double d) {
    }

    @Override
    public void update(String n, Double v) {
    }
}
