/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelNada.java
 *
 * Created on 2/Nov/2011, 17:58:21
 */
package Interface;

import Config.StringHtml;
import XML.QueryXML_Lingua;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import mvc.Observer;

/**
 *
 * @author miguel
 */
public class JPanelNada extends javax.swing.JPanel implements Observer {

    QueryXML_Lingua _l;

    /** Creates new form JPanelNada */
    public JPanelNada(QueryXML_Lingua l) {
        initComponents();
        _l = l;
        //JOptionPane.showMessageDialog(jButton1, "ola");
        changeLabel();
    }

    private void changeLabel() {
        String i = _l.queryText("nada", "jLabelInfo");
        String i_desc = _l.queryText("nada", "jLabelInfo_desc");

        jLabelInfo.setText(i);
        jLabelInfo.setToolTipText(StringHtml.html_toolTipText(i_desc));
        jLabelInfo.setHorizontalTextPosition(JLabel.CENTER);
        jLabelInfo.setVerticalTextPosition(JLabel.BOTTOM);
    }

    /** Returns an ImageIcon, or null if the path was invalid. */
    protected ImageIcon createImageIcon(String path,
            String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelInfo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(41, 41, 41));
        setLayout(new java.awt.GridBagLayout());

        jLabelInfo.setFont(new java.awt.Font("Arial", 1, 18));
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("info");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(137, 66, 150, 88);
        add(jLabelInfo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelInfo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String n) {
        if (n.equalsIgnoreCase("lng")) {
            changeLabel();
        }
    }

    @Override
    public void update(String n, Double v) {
    }

    @Override
    public void update(String material, String cor) {
    }
}
